###############################################################################
# Copyright 2015 Brient Oh @ Pristine Core
# boh@pristinecore.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
##
# config.properties
##
server.session.timeout=3600
## THYMELEAF (ThymeleafAutoConfiguration)
#spring.thymeleaf.templateResolverOrder=1
#spring.thymeleaf.check-template=true
#spring.thymeleaf.check-template-location=true
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=classpath:/views/
#spring.thymeleaf.suffix=.html 

#spring.profiles.active=prod
spring.thymeleaf.check-template-location = false
spring.thymeleaf.cache = false
spring.http.multipart.max-file-size=10MB
spring.http.multipart.max-request-size=10MB

management.port=8881
management.address=127.0.0.1
endpoints.shutdown.sensitive=false
endpoints.shutdown.enabled=true
endpoints.enabled=false
endpoints.info.enabled=true

spring.datasource.initialize=false
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:postgresql://192.168.0.79:13306/OpManagerDB?charSet=UTF-8&prepareThreshold=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.hikari.idleTimeout=10000  

mybatis.config=classpath:mybatis-config.xml
#mybatis.mapperLocations= # mappers file
#mybatis.typeAliasesPackage= # domain object's package 
#mybatis.typeHandlersPackage= # handler's package
#mybatis.check-config-location= # check the mybatis configuration exists
#mybatis.executorType= # mode of execution. Default is SIMPLE

#mybatis.typeAliasesPackage=com.i52soft.lscable.cms.domain
#mybatis.mapperLocations=classpath*:**/mappers/*.xml
#mybatis.type-aliases-package=com.example.domain.model
#mybatis.type-handlers-package=com.example.typehandler
#mybatis.configuration.map-underscore-to-camel-case=true
#mybatis.configuration.default-fetch-size=100
#mybatis.configuration.default-statement-timeout=30

#system.language.locale=ko_KR
#system.language.locale=en_KR
system.language.locale=ko_KR
system.widget.pollinginterval=60000
system.floormap.directory=/home/issac/floormaps/

system.PKISign.pubKey=/home/issac/publickey.pem
system.PKISign.progFile=/home/issac/LSCableCMS-2.0.jar
system.PKISign.sigFile=/home/issac/LSCableCMS-2.0.jar.sig

# logback configuration
logging.level.org.springframework.web=INFO
logging.level.org.thymeleaf=INFO
logging.level.com.i52soft.lscable.cms=DEBUG
logging.file=logs/lscablecms.log

#laptop
#system.server.mac=98-22-EF-5C-80-67
#testbed
#system.server.mac=00-0c-29-33-b7-df
#system.nms.ip4=http://192.168.0.91/
#system.nms.apiKey=665b19ce82741c03bb3ad1f8f396b595
#testbed-ls cable
#system.server.mac=f4-03-43-06-70-37
#system.nms.ip4=http://192.168.10.100/
#system.nms.apiKey=6c53c0081e6ac7c94e5c338b4e8f6028
#dev server
#system.server.mac=00-0c-29-b0-0d-19
system.nms.ip4=http://192.168.0.79/
system.nms.apiKey=1bdcc65c731477fe7ea53323adb59937

system.message.portup.success=스위치 포트 UP을 요청하였습니다. 잠시 기다려 주십시오
system.message.portdown.success=스위치 포트 차단을 요청하였습니다. 잠시 기다려 주십시오
system.message.portup.failure=스위치 포트 UP에 실패하였습니다. 관리자에게 문의하여 주십시오
system.message.portdown.failure=스위치 포트 차단에 실패하였습니다. 관리자에게 문의하여 주십시오
